# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/icecube/',
                'doc_host': 'https://DrHB.github.io',
                'git_url': 'https://github.com/DrHB/spine/',
                'lib_path': 'icecube'},
  'syms': {'icecube.dataset': {'icecube.dataset.good_luck': ('dataset.html#good_luck', 'icecube/dataset.py')}}}
